"""aded ended at 

Revision ID: 010f2382d8c7
Revises: 8b3cf46c14a2
Create Date: 2026-01-20 14:29:13.623397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010f2382d8c7'
down_revision: Union[str, Sequence[str], None] = '8b3cf46c14a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'ended_at')
    # ### end Alembic commands ###
