"""added completed bol and chanhged the end value to null at start 

Revision ID: 8b3cf46c14a2
Revises: 8438b18d002b
Create Date: 2026-01-20 14:14:44.488792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b3cf46c14a2'
down_revision: Union[str, Sequence[str], None] = '8438b18d002b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    op.alter_column('todo', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
